

  runtime: python
  env: flex
  entrypoint: gunicorn -b :$PORT main:app

  runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.12"

  manual_scaling:
  instances: 1

# Additional configuration (optional)
  handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
